# NumPy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

## NumPy Operation

In [8]:
a=np.array([(1,2,3),(4,5,6)])
a.ndim

2

In [9]:
a=np.array([(1,2,3),(4,5,6)])
a.itemsize

4

In [10]:
a=np.array([(1,2,3),(4,5,6)])
a.dtype

dtype('int32')

In [11]:
a=np.array([(1,2,3),(4,5,6)])
a.size

6

In [12]:
a=np.array([(1,2,3),(4,5,6)])
a.shape

(2, 3)

In [15]:
a=np.array([(1,2,3),(4,5,6)])
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a=np.array([(1,2,3),(4,5,6)])
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
a=np.array([(1,2,3),(4,5,6)])
a[0,2]

3

In [32]:
a=np.array([(1,2,3),(4,5,6)])
a[0:,1]

array([2, 5])

In [45]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a[0:1 ,1]

array([2])

In [46]:
#feel the difference
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a[0:2 ,1]

array([2, 4])

In [47]:
#feel the difference
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a[0:3 ,1]

array([2, 4, 6])

In [48]:
#feel the difference
a=np.array([(1,2),(3,4),(5,6),(7,8),(9,10),(11,12),(13,14)])
a[0:5 ,1]

array([ 2,  4,  6,  8, 10])

In [49]:
a=np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [51]:
a=np.array([1,2,3])
a.min()

1

In [52]:
a=np.array([1,2,3])
a.max()

3

In [53]:
a=np.array([1,2,3])
a.sum()

6

In [55]:
#CONCEPT OF AXES IN NumPy
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a=np.array([(1,2,3),(4,5,6)])
a.sum(axis=0)

array([5, 7, 9])

In [58]:
a=np.array([(1,2,3),(4,5,6)])
a.sum(axis=1)

array([ 6, 15])

In [61]:
a=np.array([(1,2,3),(4,5,6)])
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [65]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(4,5,6),(7,8,9)])
c = x+y
d = x-y
e = x/y
f = x*y

print(c)
print(d)
print(e)
print(f)

[[ 5  7  9]
 [11 13 15]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
[[ 4 10 18]
 [28 40 54]]


### Vertical Stacking

In [68]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(4,5,6),(7,8,9)])
np.vstack((x,y)) #for vertical stacking

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(4,5,6),(7,8,9)])
np.hstack((x,y)) #for horizontal stacking

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])